name: SupernaturalPlayers
main: me.matterz.supernaturals.SupernaturalsPlugin
version: 2.2.6
author: Matterz
commands:
  sn:
    description: Supernatural commands
    usage: /<command> - lists commands