name: SupernaturalPlayers
main: me.matterz.supernaturals.SupernaturalsPlugin
version: 1.0.3
author: Matterz
commands:
  sn:
    description: Supernatural commands
    usage: /<command> - lists commands